version: '3'

services:

  api:
    build:
      context: .
      dockerfile: build/Dockerfile
    environment:
      GUNICORN_RELOAD: "False"
      RUNNING_ENV: "prod"
      LOG_LOCAL: "False" # External logging like IP
      LOG_LEVEL: 20
      LOGGER_SWAGGER: "False" # Unnecessary logging
      FASTAPI_ROOT_PATH: ""
    ports:
      - 8080:8080
    networks:
      - backend


networks:
  backend:
    driver: bridge
